import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const now = new Date();
    
    const sampleTransactions = [
        // User 1 Transactions
        {
            userId: 1,
            type: 'transfer',
            amount: 2.5,
            recipientPhone: '+19876543210',
            recipientUdi: '@priya',
            network: null,
            fee: 50,
            cost: null,
            validity: null,
            status: 'completed',
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 1,
            type: 'recharge',
            amount: 84,
            recipientPhone: null,
            recipientUdi: null,
            network: 'Jio',
            fee: 0,
            cost: 3099,
            validity: 84,
            status: 'completed',
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 1,
            type: 'transfer',
            amount: 1.0,
            recipientPhone: '+19998887777',
            recipientUdi: null,
            network: null,
            fee: 25,
            cost: null,
            validity: null,
            status: 'completed',
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 1,
            type: 'recharge',
            amount: 1.5,
            recipientPhone: null,
            recipientUdi: null,
            network: 'Airtel',
            fee: 0,
            cost: 239,
            validity: 28,
            status: 'completed',
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 1,
            type: 'transfer',
            amount: 0.5,
            recipientPhone: null,
            recipientUdi: '@john',
            network: null,
            fee: 15,
            cost: null,
            validity: null,
            status: 'completed',
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // User 2 Transactions
        {
            userId: 2,
            type: 'recharge',
            amount: 2.0,
            recipientPhone: null,
            recipientUdi: null,
            network: 'Vi',
            fee: 0,
            cost: 299,
            validity: 28,
            status: 'completed',
            createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            type: 'transfer',
            amount: 3.0,
            recipientPhone: '+12345678900',
            recipientUdi: '@sainadh',
            network: null,
            fee: 75,
            cost: null,
            validity: null,
            status: 'completed',
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            type: 'recharge',
            amount: 1.5,
            recipientPhone: null,
            recipientUdi: null,
            network: 'BSNL',
            fee: 0,
            cost: 199,
            validity: 30,
            status: 'completed',
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            type: 'transfer',
            amount: 1.5,
            recipientPhone: '+15556667777',
            recipientUdi: null,
            network: null,
            fee: 40,
            cost: null,
            validity: null,
            status: 'pending',
            createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            type: 'transfer',
            amount: 0.8,
            recipientPhone: null,
            recipientUdi: '@mike',
            network: null,
            fee: 20,
            cost: null,
            validity: null,
            status: 'completed',
            createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            type: 'recharge',
            amount: 6.0,
            recipientPhone: null,
            recipientUdi: null,
            network: 'Jio',
            fee: 0,
            cost: 666,
            validity: 56,
            status: 'completed',
            createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            type: 'transfer',
            amount: 2.0,
            recipientPhone: '+14445556666',
            recipientUdi: null,
            network: null,
            fee: 50,
            cost: null,
            validity: null,
            status: 'completed',
            createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});